In [7]:
import h2o
h2o.init()

df = h2o.import_file("C:/Temp/all_real_quad_fields.csv")

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         9 mins 22 secs
H2O_cluster_timezone:       Europe/Berlin
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.5
H2O_cluster_version_age:    10 days
H2O_cluster_name:           H2O_from_python_esultano_8b8jz1
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    6.914 Gb
H2O_cluster_total_cores:    12
H2O_cluster_allowed_cores:  12
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.8.11 final
--------------------------  ---------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [30]:
df_all = df[df['class_number'] <= 2]
print(df_all['class_number'].table())
df_all = df_all.split_frame([0.25])[0]
print(df_all['class_number'].table())

class_number,Count
1,177159
2,183432

class_number,Count
1,44262
2,45974

## Read data

In [31]:
train, test = df_all.split_frame([0.7], seed=42)

In [5]:
# Columns are:
# 'defining_polynomial'
# 'class_number'
# 'discriminant'
# 'res_s=0'
# 'number_roots_unity'
# 'regulator'
# 'a_1', 'a_2', 'a_3', ..., 'a_1000'

#print(df.columns.tolist())
#print(df.iloc[0:3, np.r_[0,1,2,3,4,5,6,7,8,9,10,11:13]])

In [32]:
x = [f'a_{i}' for i in range(1,1001)]
y = "class_number"

In [33]:
from h2o.estimators import H2ORandomForestEstimator
rf = H2ORandomForestEstimator(ntrees=10)
rf.train(x=x,
         y=y,
         training_frame=train,
         validation_frame=test)
print(rf)

C:\Development\Anaconda3\lib\site-packages\h2o\estimators\estimator_base.py:201: RuntimeWarning: Dropping bad and constant columns: [a_1]
  warnings.warn(mesg["message"], RuntimeWarning)

drf Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  DRF_model_python_1629023006308_3


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,641871.0,20.0,20.0,20.0,4793.0,5505.0,5111.9

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 0.225775541751117
RMSE: 0.475158438577194
MAE: 0.36006127642433894
RMSLE: 0.19388845421739212
Mean Residual Deviance: 0.225775541751117

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 0.18722845013015096
RMSE: 0.43269902949989497
MAE: 0.3621833749442854
RMSLE: 0.1767665916692612
Mean Residual Deviance: 0.18722845013015096

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2021-08-15 18:25:09,0.006 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2021-08-15 18:25:14,5.718 sec,1.0,0.570126,0.357695,0.325044,0.575566,0.363640,0.331277
2,,2021-08-15 18:25:20,11.721 sec,2.0,0.555427,0.353898,0.308499,0.503165,0.361863,0.253175
3,,2021-08-15 18:25:26,17.549 sec,3.0,0.539743,0.354822,0.291323,0.473998,0.361269,0.224674
4,,2021-08-15 18:25:33,24.320 sec,4.0,0.531194,0.358046,0.282167,0.462229,0.363866,0.213656
5,,2021-08-15 18:25:39,30.686 sec,5.0,0.521576,0.359785,0.272042,0.453256,0.363687,0.205441
6,,2021-08-15 18:25:46,36.824 sec,6.0,0.510243,0.359230,0.260348,0.445755,0.362637,0.198698
7,,2021-08-15 18:25:52,42.833 sec,7.0,0.499763,0.359743,0.249763,0.441139,0.362367,0.194603
8,,2021-08-15 18:25:58,49.257 sec,8.0,0.490899,0.360029,0.240982,0.437828,0.362319,0.191694
9,,2021-08-15 18:26:06,56.934 sec,9.0,0.482455,0.360180,0.232763,0.435568,0.362957,0.189720
10,,2021-08-15 18:26:12,1 min 2.948 sec,10.0,0.475158,0.360061,0.225776,0.432699,0.362183,0.187228

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0     a_490          1602.931641           1.000000    0.017549
1     a_900          1302.926392           0.812840    0.014265
2     a_405          1099.720459           0.686068    0.012040
3     a_640           955.246094           0.595937    0.010458
4      a_90           715.314331           0.446254    0.007831
5     a_180           704.110107           0.439264    0.007709
6     a_250           693.812622           0.432840    0.007596
7      a_45           680.761902           0.424698    0.007453
8     a_221           659.953552           0.411717    0.007225
9      a_50           621.488281           0.387720    0.006804
10     a_10           586.276001           0.365752    0.006419
11     a_80           570.640259           0.355998    0.006248
12     a_13           524.739502           0.327362    0.005745
13    a_884           510.638550           0.318565    0.005591
14    a_125           503.623901           0.314189    0.005514
15     a_40           497.330353           0.310263    0.005445
16    a_500           493.337006           0.307772    0.005401
17    a_605           471.084167           0.293889    0.005158
18    a_100           443.511749           0.276688    0.004856
19    a_160           367.952789           0.229550    0.004028

See the whole table with table.as_data_frame()

In [35]:
from h2o.automl import H2OAutoML

'maybe include GLM later'
autoML = H2OAutoML(max_runtime_secs=18000, include_algos=["GBM", "DRF"], balance_classes=False)
autoML.train(x=x, y=y, training_frame=df_all)
leaderboard = autoML.leaderboard
print(leaderboard)

AutoML progress: |████████